global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
    - targets: ['pushgateway:9091']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'host'
    static_configs:
    - targets: ['host-monitoring:9100']

  - job_name: 'user_online'
    scrape_interval: 1s
    static_configs:
    - targets: ['user-online:9101']

  - job_name: 'user_online_sabina'
    scrape_interval: 1s
    static_configs:
    - targets: ['user-online-sabina:9101']

  - job_name: 'user_online_marshal'
    scrape_interval: 1s
    static_configs:
    - targets: ['user-online-marshal:9101']
